### PR TITLE
Add Custom Color Modifications

### PR DESCRIPTION
**Pull request by ThatHypedPerson**
This is just a basic implementation of all the things I think should have options to be colored so far. I also currently have colors working for Tatl and the File Select screen, but I'm not sure if I should add them here.

I think that any logic/presets for the colors should be handled via the apworld rather than the mod since they are being sent anyways, and they should also default to vanilla colors if nothing is provided.

### CODE REVIEW

**Comment by LittleCube-hax** [comment]
Holy hell, this is legit.

I'd love to also have your Tatl and File Select changes as well, if you're willing to push them.

When this gets merged, for now I'll add code to handle the settings through the YAML, but eventually this code will probably be used for a standalone color mod with its own UI for setting it whenever the player wishes.

**Comment by ThatHypedPerson** [comment]
Alright I went ahead and added them.

Also I agree that when the GUI for mods is released that this should be its own mod, so I'll be keeping my own repo updated in parallel for when that time comes.

**Comment by ThatHypedPerson** [comment]
I'm currently working on getting other forms working, but I've hit a bit of a roadblock.

I've gotten Deku Link theoretically working by reusing the grayscale textures of Human Link, but currently I can only get it to work by manually adding the texture via code rather than reusing the texture from the game.
image
Trying to directly reuse the textures instead seems to corrupt them.
image
The easiest solution is to include these assets in the mod (which would also make adding/modifying everything else a hell of a lot easier), but I don't really like that solution since it would probably be better to not include those assets if necessary.

It'd be nice to get a consensus on whether or not to include these texture assets in a mod like this since I can (nearly) implement every other form easily.

**Comment by LittleCube-hax** [comment]
Sorry, just saw these other comments.

That looks great! I'd happily accept any implementation you have that works with Deku/Goron at least if possible.

As for the texture inclusion question, I'll take it back to HQ and see what the bois think 👀

**Comment by ThatHypedPerson** [comment]
I'll probably hold off on adding the other forms until there's more modding documentation. Mainly, I'm not sure how most ideas I have so far to implement them would work with texture packs.

Also completely forgot to commit a few more changes I made so I'll go ahead and add those right now. I think currently its in a state that should be good to merge, but since nearly everything outside of player models are easy enough to modify I might add them in as well.

I was also thinking if these additions should be in a standalone mod that interfaces with something like `MMRecompAPCppGlue` instead of within this mod. It could still be included with the other mods in releases, but it would also make it easier in the future when we're able to add a UI to it. Let me know what you think of that though.

**Comment by LittleCube-hax** [comment]
Closing due to integration as a separate mod.

**Pull request closed without merging**
